AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "lib/flexr/codegen/**/*"
    - "lib/flexr/unicode/data/**/*"
    - "lib/flexr/regexp/tokenizer.rb"
    - "spec/fixtures/generated.rb"
    - "vendor/**/*"

Metrics/MethodLength:
  Max: 80

Metrics/ClassLength:
  Max: 250

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics:
  Enabled: false

Layout:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false
