# frozen_string_literal: true

module Flexr
  module Codegen
    class Table < Base
      def generate(state: :initial)
        machine = compiled.machines.fetch(state)
        dfa = machine.dfa
        {
          ec: dfa.ec,
          nxt: dfa.transitions.flatten.map { |value| value || -1 },
          acc: dfa.accepts.map { |rules| rules.first&.rule_index || -1 },
          start: dfa.start,
          states: dfa.states,
          classes: dfa.class_count
        }.freeze
      end

      def header(source: nil, backend: :table)
        stat = stats.fetch(:initial, {})
        [
          "# Generated by flexr. DO NOT EDIT.",
          "# source: #{source}",
          "# backend: #{backend} / states: #{stat[:states]} / byte-classes: #{stat[:classes]}"
        ].join("\n")
      end

      def source(indent: "  ")
        lines = []
        lines << "#{indent}def scan_one"
        lines << "#{indent}  return Flexr::Runtime::Interpreter.new(self).scan unless __flexr_generated_fast_path?"
        lines << "#{indent}  machine = self.class.__flexr_compiled.machines.fetch(state)"
        lines << "#{indent}  dfa = machine.dfa"
        lines << "#{indent}  position = byte_pos"
        lines << "#{indent}  return nil unless valid_utf8_at?(position)"
        lines << "#{indent}  cursor = position"
        lines << "#{indent}  current = dfa.start"
        lines << "#{indent}  direct = dfa.direct"
        lines << "#{indent}  source = buffer.source"
        simple = if simple_fast_path?
          lines << "#{indent}  best = nil"
          true
        else
          lines << "#{indent}  best = __flexr_generated_acceptance(dfa, current, position, position, nil)"
          false
        end
        lines << "#{indent}  accelerate = self.class.__flexr_config.options.fetch(:accel, :auto) != :none && !utf8_input?"
        lines << "#{indent}  while cursor < source.bytesize || buffer.ensure_available?(cursor + 1)"
        lines << "#{indent}    if accelerate"
        lines << "#{indent}      region = __flexr_generated_acceleration_region(dfa, current)"
        lines << "#{indent}      accelerated_end = __flexr_generated_accelerate(region, cursor) if region"
        lines << "#{indent}      if accelerated_end && accelerated_end > cursor"
        lines << "#{indent}        cursor = accelerated_end"
        lines << "#{indent}        best = __flexr_generated_acceptance(dfa, current, position, cursor, best)"
        lines << "#{indent}        next"
        lines << "#{indent}      end"
        lines << "#{indent}    end"
        lines << "#{indent}    byte = source.getbyte(cursor)"
        lines << "#{indent}    current = if direct"
        lines << "#{indent}      class_id = dfa.ec[byte]"
        lines << "#{indent}      value = direct[:nxt][(current * direct[:classes]) + class_id]"
        lines << "#{indent}      value >= 0 ? value : nil"
        lines << "#{indent}    else"
        lines << "#{indent}      dfa.transition(current, byte)"
        lines << "#{indent}    end"
        lines << "#{indent}    break unless current"
        lines << "#{indent}    cursor += 1"
        if simple
          lines << "#{indent}    acceptance = dfa.accepts[current].first"
          lines << "#{indent}    if acceptance"
          lines << "#{indent}      rule = self.class.__flexr_rules.fetch(acceptance.rule_index)"
          lines << "#{indent}      best ||= (@__flexr_generated_match ||= Flexr::Runtime::Match.new)"
          lines << "#{indent}      best.rule = rule"
          lines << "#{indent}      best.start_pos = position"
          lines << "#{indent}      best.end_pos = cursor"
          lines << "#{indent}      best.total_end_pos = cursor"
          lines << "#{indent}    end"
        else
          lines << "#{indent}    best = __flexr_generated_acceptance(dfa, current, position, cursor, best)"
        end
        lines << "#{indent}  end"
        lines << "#{indent}  best"
        lines << "#{indent}end"
        lines << "#{indent}def __flexr_generated_acceleration_region(dfa, state)"
        lines << "#{indent}  @__flexr_generated_accel_regions ||= {}"
        lines << "#{indent}  regions = (@__flexr_generated_accel_regions[dfa] ||= Flexr::Automaton::Accel.extract(dfa).to_h { |region| [region.state, region] })"
        lines << "#{indent}  region = regions[state]"
        lines << "#{indent}  return unless region"
        lines << "#{indent}  return if dfa.accepts[state].any? do |acceptance|"
        lines << "#{indent}    rule = self.class.__flexr_rules.fetch(acceptance.rule_index)"
        lines << "#{indent}    acceptance.bol_only || acceptance.end_anchor || rule.trailing"
        lines << "#{indent}  end"
        lines << "#{indent}  region"
        lines << "#{indent}end"
        lines << "#{indent}def __flexr_generated_accelerate(region, position)"
        lines << "#{indent}  binary = buffer.source.b"
        lines << "#{indent}  mode = self.class.__flexr_config.options.fetch(:accel, :auto)"
        lines << "#{indent}  match_end = if %i[strscan auto].include?(mode) && defined?(::StringScanner)"
        lines << "#{indent}    scanner = ::StringScanner.new(binary)"
        lines << "#{indent}    scanner.pos = position"
        lines << "#{indent}    length = scanner.skip(region.regexp)"
        lines << "#{indent}    length && scanner.pos"
        lines << "#{indent}  else"
        lines << "#{indent}    match = region.regexp.match(binary, position)"
        lines << "#{indent}    match && match.begin(0) == position ? match.end(0) : nil"
        lines << "#{indent}  end"
        lines << "#{indent}  return match_end if match_end && match_end < buffer.bytesize"
        lines << "#{indent}  return match_end if match_end && buffer.eof_loaded?"
        lines << "#{indent}  return unless buffer.ensure_available?(buffer.bytesize + 1)"
        lines << "#{indent}  __flexr_generated_accelerate(region, position)"
        lines << "#{indent}rescue ArgumentError"
        lines << "#{indent}  nil"
        lines << "#{indent}end"
        lines << "#{indent}def __flexr_generated_fast_path?"
        lines << "#{indent}  return @__flexr_generated_fast_path if defined?(@__flexr_generated_fast_path)"
        lines << "#{indent}  @__flexr_generated_fast_path = if self.class.__flexr_config.backend == :firstmatch ||"
        lines << "#{indent}                                  self.class.__flexr_config.options[:allow_empty_match] == true"
        lines << "#{indent}    false"
        lines << "#{indent}  else"
        lines << "#{indent}    self.class.__flexr_rules.none? do |rule|"
        lines << "#{indent}      !rule.trailing.nil? || rule.patterns.any? do |pattern|"
        lines << "#{indent}        next false unless pattern.is_a?(::Regexp)"
        lines << "#{indent}      next true if pattern.source.match?(/\\\\[pP]\\\\{/) || pattern.source.match?(/\\[:(?:\\^)?[a-z]+:\\]/)"
        lines << "#{indent}        self.class.__flexr_config.options[:unicode] == true && utf8_input? && pattern.source.match?(/\\\\[dDwWsS]/)"
        lines << "#{indent}      end"
        lines << "#{indent}    end"
        lines << "#{indent}  end"
        lines << "#{indent}end"
        lines << "#{indent}def __flexr_generated_acceptance(dfa, state, start_position, cursor, best)"
        lines << "#{indent}  dfa.accepts[state].each do |acceptance|"
        lines << "#{indent}    next if acceptance.bol_only && !beginning_of_line?"
        lines << "#{indent}    next if acceptance.end_anchor && !(buffer.eof?(cursor) || buffer.getbyte(cursor) == 0x0a)"
        lines << "#{indent}    rule = self.class.__flexr_rules.fetch(acceptance.rule_index)"
        lines << "#{indent}    defer_token_size_check!(cursor - start_position)"
        lines << "#{indent}    next if best && cursor < best.total_end_pos"
        lines << "#{indent}    next if best && cursor == best.total_end_pos &&"
        lines << "#{indent}      rule.index > best.rule.index"
        lines << "#{indent}    best ||= (@__flexr_generated_match ||= Flexr::Runtime::Match.new)"
        lines << "#{indent}    best.rule = rule"
        lines << "#{indent}    best.start_pos = start_position"
        lines << "#{indent}    best.end_pos = cursor"
        lines << "#{indent}    best.total_end_pos = cursor"
        lines << "#{indent}  end"
        lines << "#{indent}  best"
        lines << "#{indent}end"
        "#{lines.join("\n")}\n"
      end

      def simple_fast_path?
        compiled.rules.all? do |rule|
          rule.trailing.nil? && rule.pattern_conditions.all? do |condition|
            condition && !condition.bol_only && !condition.end_anchor
          end
        end
      end
    end
  end
end
