# frozen_string_literal: true

module Flexr
  module Codegen
    class Table < Base
      def generate(state: :initial)
        machine = compiled.machines.fetch(state)
        dfa = machine.dfa
        {
          ec: dfa.ec,
          nxt: dfa.transitions.flatten.map { |value| value || -1 },
          acc: dfa.accepts.map { |rules| rules.first&.rule_index || -1 },
          start: dfa.start,
          states: dfa.states,
          classes: dfa.class_count
        }.freeze
      end

      def header(source: nil, backend: :table)
        stat = stats.fetch(:initial, {})
        [
          "# Generated by flexr. DO NOT EDIT.",
          "# source: #{source}",
          "# backend: #{backend} / states: #{stat[:states]} / byte-classes: #{stat[:classes]}"
        ].join("\n")
      end

      def source(indent: "  ")
        lines = []
        lines << "#{indent}def scan_one"
        lines << "#{indent}  return Flexr::Runtime::Interpreter.new(self).scan unless __flexr_generated_fast_path?"
        lines << "#{indent}  machine = self.class.__flexr_compiled.machines.fetch(state)"
        lines << "#{indent}  dfa = machine.dfa"
        lines << "#{indent}  position = byte_pos"
        lines << "#{indent}  return nil unless valid_utf8_at?(position)"
        lines << "#{indent}  cursor = position"
        lines << "#{indent}  current = dfa.start"
        lines << "#{indent}  best = __flexr_generated_acceptance(dfa, current, position, position, nil)"
        lines << "#{indent}  while buffer.ensure_available?(cursor + 1)"
        lines << "#{indent}    byte = buffer.getbyte(cursor)"
        lines << "#{indent}    current = if self.class.__flexr_config.backend == :direct"
        lines << "#{indent}      dfa.transition_direct(current, byte)"
        lines << "#{indent}    else"
        lines << "#{indent}      dfa.transition(current, byte)"
        lines << "#{indent}    end"
        lines << "#{indent}    break unless current"
        lines << "#{indent}    cursor += 1"
        lines << "#{indent}    best = __flexr_generated_acceptance(dfa, current, position, cursor, best)"
        lines << "#{indent}  end"
        lines << "#{indent}  best"
        lines << "#{indent}end"
        lines << "#{indent}def __flexr_generated_fast_path?"
        lines << "#{indent}  return false if self.class.__flexr_config.backend == :firstmatch"
        lines << "#{indent}  self.class.__flexr_rules.none? do |rule|"
        lines << "#{indent}    !rule.trailing.nil? || rule.patterns.any? do |pattern|"
        lines << "#{indent}      pattern.is_a?(Regexp) && (pattern.source.include?(\"\\\\p{\") || pattern.source.match?(/\\[:(?:\\^)?[a-z]+:\\]/))"
        lines << "#{indent}    end"
        lines << "#{indent}  end"
        lines << "#{indent}end"
        lines << "#{indent}def __flexr_generated_acceptance(dfa, state, start_position, cursor, best)"
        lines << "#{indent}  dfa.accepts[state].each do |acceptance|"
        lines << "#{indent}    next if acceptance.bol_only && !beginning_of_line?"
        lines << "#{indent}    next unless utf8_boundary?(cursor)"
        lines << "#{indent}    next if acceptance.end_anchor && !(buffer.eof?(cursor) || buffer.getbyte(cursor) == 0x0a)"
        lines << "#{indent}    rule = self.class.__flexr_rules.fetch(acceptance.rule_index)"
        lines << "#{indent}    defer_token_size_check!(cursor - start_position)"
        lines << "#{indent}    candidate = Flexr::Runtime::Match.new(rule: rule, start_pos: start_position,"
        lines << "#{indent}      end_pos: cursor, total_end_pos: cursor)"
        lines << "#{indent}    next if best && candidate.total_end_pos < best.total_end_pos"
        lines << "#{indent}    next if best && candidate.total_end_pos == best.total_end_pos &&"
        lines << "#{indent}      candidate.rule.index > best.rule.index"
        lines << "#{indent}    best = candidate"
        lines << "#{indent}  end"
        lines << "#{indent}  best"
        lines << "#{indent}end"
        "#{lines.join("\n")}\n"
      end
    end
  end
end
