# frozen_string_literal: true
# Generated by flexr. DO NOT EDIT.
# source: spec/fixtures/generated.flexr.rb
# spec-digest: sha256:3f55f6527e5ba91ad01057847847a8c19354e901ebeb129be3b7b94fd931199f
# artifact-schema: 1
# runtime-abi: 1
# unicode: 15.1.0
# backend: table
# compiled: true
# eval: false
# standalone: false

require "flexr"

module GeneratedFixture
  class Lexer < Flexr::Lexer
    DIGIT = /[0-9]/
    Flexr::Generated.install_compiled!(self, { artifact: {schema_version: 1, compiler_version: "1.0.0", runtime_abi_version: 1, unicode_version: "15.1.0"}, rules: [{ index: 0, patterns: [/(?-imx:[0-9])+/], pattern_conditions: [[0, 0, false, false]], trailing: nil, action: proc{ emit :INT, text.to_i }, states: [:initial], bol_only: false, end_anchor: nil }], backend: :table, token_kind: :array, encoding: Encoding::UTF_8, declared_tokens: [], options: {}, eof_rules: {  }, states: [], inclusive_states: {initial: true}, compiled: { machines: { :initial => { state_name: :initial, dfa: {accepts: [[], [[0, 0, false, false]]], ec: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], class_count: 3, state_count: 2, start: 0, rule_ids: [0], packed: {base: [0, 1], default: [nil, nil], next: [nil, 1, 1], check: [nil, 0, 1]}} } }, states: [:initial], stats: {initial: {states: 2, classes: 3, accepting_states: 1}}, diagnostics: [] } })
    def scan_one
      if @__flexr_generated_scan_state != @state
        machine = self.class.__flexr_compiled.machines.fetch(@state)
        @__flexr_generated_scan_state = @state
        @__flexr_generated_scan_dfa = machine.dfa
        @__flexr_generated_scan_fast = __flexr_generated_fast_path?(@__flexr_generated_scan_dfa)
        @__flexr_generated_scan_simple = __flexr_generated_simple_fast_path?(@__flexr_generated_scan_dfa)
      end
      dfa = @__flexr_generated_scan_dfa
      return Flexr::Runtime::Interpreter.new(self).scan unless @__flexr_generated_scan_fast
      position = byte_pos
      return nil unless valid_utf8_at?(position)
      return __flexr_generated_scan_simple(dfa, position) if @__flexr_generated_scan_simple
      cursor = position
      current = dfa.start
      direct = dfa.direct
      direct_nxt = direct&.fetch(:nxt)
      direct_classes = direct&.fetch(:classes)
      ec = dfa.ec
      source = buffer.stable_source
      guarded_steps = scan_steps_guarded?
      token_start = more_text_start || position
      token_limit = max_token_size
      check_token_limit = token_limit_required?
      best = nil
      accel_mode = @accel_mode
      accelerate = accel_mode != :none && !(accel_mode == :auto && @__flexr_generated_auto_accel_off)
      while cursor < (source ? source.bytesize : buffer.bytesize) || buffer.ensure_available?(cursor + 1)
        if accelerate
          region = __flexr_generated_acceleration_region(dfa, current)
          acceptance = dfa.accepts[current].first
          token_rule = acceptance&.rule_index
          accelerated_end = __flexr_generated_accelerate(region, cursor, token_rule, position) if region
          if accelerated_end && accelerated_end > cursor
            cursor = accelerated_end
            best = __flexr_generated_acceptance(dfa, current, position, cursor, best)
            next
          end
        end
        byte = source ? source.getbyte(cursor) : buffer.getbyte(cursor)
        consume_step! if guarded_steps
        current = if direct_nxt
          class_id = ec[byte]
          value = direct_nxt[(current * direct_classes) + class_id]
          value >= 0 ? value : nil
        else
          dfa.transition(current, byte)
        end
        break unless current
        cursor += 1
        resource_acceptance = dfa.accepts[current].first
        resource_rule = resource_acceptance&.rule_index
        if check_token_limit
          size = cursor - token_start
          defer_token_size_check!(size, rule: resource_rule) if size > token_limit
        end
        best = __flexr_generated_acceptance(dfa, current, position, cursor, best)
      end
      best
    end
    def __flexr_generated_scan_simple(dfa, position)
      current = dfa.start
      direct = dfa.direct
      direct_nxt = direct&.fetch(:nxt)
      direct_classes = direct&.fetch(:classes)
      ec = dfa.ec
      accepts = dfa.accepts
      rules = self.class.__flexr_rules
      source = buffer.stable_source
      guarded_steps = scan_steps_guarded?
      token_start = more_text_start || position
      token_limit = max_token_size
      check_token_limit = token_limit_required?
      cursor = position
      best = nil
      accel_mode = @accel_mode
      accelerate = accel_mode != :none && !(accel_mode == :auto && @__flexr_generated_auto_accel_off)
      if source && !guarded_steps && !check_token_limit && !accelerate
        while cursor < source.bytesize
          byte = source.getbyte(cursor)
          current = if direct_nxt
            class_id = ec[byte]
            value = direct_nxt[(current * direct_classes) + class_id]
            value >= 0 ? value : nil
          else
            dfa.transition(current, byte)
          end
          break unless current
          cursor += 1
          acceptance = accepts[current].first
          next unless acceptance
          rule = rules.fetch(acceptance.rule_index)
          best ||= (@__flexr_generated_match ||= Flexr::Runtime::Match.new)
          best.rule = rule
          best.start_pos = position
          best.end_pos = cursor
          best.total_end_pos = cursor
        end
        return best
      end
      while cursor < (source ? source.bytesize : buffer.bytesize) || buffer.ensure_available?(cursor + 1)
        if accelerate
          region = __flexr_generated_acceleration_region(dfa, current)
          acceptance = accepts[current].first
          accelerated_end = __flexr_generated_accelerate(region, cursor, acceptance&.rule_index, position) if region
          if accelerated_end && accelerated_end > cursor
            cursor = accelerated_end
            best = __flexr_generated_acceptance(dfa, current, position, cursor, best)
            next
          end
        end
        byte = source ? source.getbyte(cursor) : buffer.getbyte(cursor)
        consume_step! if guarded_steps
        current = if direct_nxt
          class_id = ec[byte]
          value = direct_nxt[(current * direct_classes) + class_id]
          value >= 0 ? value : nil
        else
          dfa.transition(current, byte)
        end
        break unless current
        cursor += 1
        acceptance = accepts[current].first
        if check_token_limit
          size = cursor - token_start
          defer_token_size_check!(size, rule: acceptance&.rule_index) if size > token_limit
        end
        next unless acceptance
        rule = rules.fetch(acceptance.rule_index)
        best ||= (@__flexr_generated_match ||= Flexr::Runtime::Match.new)
        best.rule = rule
        best.start_pos = position
        best.end_pos = cursor
        best.total_end_pos = cursor
      end
      best
    end
    def __flexr_generated_acceleration_region(dfa, state)
      @__flexr_generated_accel_regions ||= {}
      regions = (@__flexr_generated_accel_regions[dfa] ||= Flexr::Automaton::Accel.extract(dfa).to_h { |region| [region.state, region] })
      region = regions[state]
      return unless region
      return if @__flexr_generated_disabled_auto_accel&.key?(region)
      return if utf8_input? && region.bytes.any? { |byte| byte >= 128 }
      return if dfa.accepts[state].any? do |acceptance|
        rule = self.class.__flexr_rules.fetch(acceptance.rule_index)
        acceptance.bol_only || acceptance.end_anchor || rule.trailing
      end
      region
    end
    def __flexr_generated_accelerate(region, position, token_rule, token_start)
      mode = @accel_mode
      cursor = position
      matched = false
      loop do
        if cursor >= buffer.bytesize
          return matched ? cursor : nil if buffer.eof_loaded?
          return matched ? cursor : nil unless buffer.ensure_available?(cursor + 1)
        end
        segment = buffer.source
        segment_position = cursor - buffer.base_offset
        if segment.encoding == ::Encoding::UTF_8 && region.utf8_regexp
          regexp = region.utf8_regexp
        else
          segment = segment.b unless segment.encoding == ::Encoding::BINARY
          regexp = region.regexp
        end
        length = begin
          if %i[strscan auto].include?(mode) && defined?(::StringScanner)
            @__flexr_generated_accel_scanner ||= ::StringScanner.new("".b)
            @__flexr_generated_accel_scanner.string = segment
            @__flexr_generated_accel_scanner.pos = segment_position
            @__flexr_generated_accel_scanner.skip(regexp)
          else
            match = regexp.match(segment, segment_position)
            match && match.begin(0) == segment_position ? match.end(0) - segment_position : nil
          end
        rescue ArgumentError
          nil
        end
        __flexr_generated_record_auto_accel_miss(region) if mode == :auto && length.to_i < 8
        return matched ? cursor : nil unless length&.positive?
        matched = true
        cursor += length
        consume_step!(length)
        defer_token_size_check!(cursor - (more_text_start || token_start), rule: token_rule)
        return cursor if cursor < buffer.bytesize || buffer.eof_loaded?
      end
    end
    def __flexr_generated_record_auto_accel_miss(region)
      @__flexr_generated_auto_accel_misses ||= Hash.new(0)
      @__flexr_generated_auto_accel_misses[region] += 1
      @__flexr_generated_auto_accel_miss_total = @__flexr_generated_auto_accel_miss_total.to_i + 1
      @__flexr_generated_auto_accel_off = true if @__flexr_generated_auto_accel_miss_total >= 9
      return if @__flexr_generated_auto_accel_misses[region] < 3
      @__flexr_generated_disabled_auto_accel ||= {}
      @__flexr_generated_disabled_auto_accel[region] = true
    end
    def __flexr_generated_fast_path?(dfa)
      @__flexr_generated_fast_paths ||= {}
      return @__flexr_generated_fast_paths[dfa] if @__flexr_generated_fast_paths.key?(dfa)
      rules = dfa.rule_ids.map { |rule_index| self.class.__flexr_rules.fetch(rule_index) }
      @__flexr_generated_fast_paths[dfa] = self.class.__flexr_config.backend != :firstmatch &&
        self.class.__flexr_config.options[:allow_empty_match] != true && rules.none?(&:trailing)
    end
    def __flexr_generated_simple_fast_path?(dfa)
      @__flexr_generated_simple_fast_paths ||= {}
      return @__flexr_generated_simple_fast_paths[dfa] if @__flexr_generated_simple_fast_paths.key?(dfa)
      rules = dfa.rule_ids.map { |rule_index| self.class.__flexr_rules.fetch(rule_index) }
      @__flexr_generated_simple_fast_paths[dfa] = rules.all? do |rule|
        rule.pattern_conditions.all? { |condition| condition && !condition.bol_only && !condition.end_anchor }
      end
    end
    def __flexr_generated_acceptance(dfa, state, start_position, cursor, best)
      dfa.accepts[state].each do |acceptance|
        next if acceptance.bol_only && !beginning_of_line?
        next if acceptance.end_anchor && !(buffer.eof?(cursor) || buffer.getbyte(cursor) == 0x0a)
        rule = self.class.__flexr_rules.fetch(acceptance.rule_index)
        next if best && cursor < best.total_end_pos
        next if best && cursor == best.total_end_pos &&
          rule.index > best.rule.index
        best ||= (@__flexr_generated_match ||= Flexr::Runtime::Match.new)
        best.rule = rule
        best.start_pos = start_position
        best.end_pos = cursor
        best.total_end_pos = cursor
      end
      best
    end
    def __flexr_generated_execute(rule)
      case rule.index
      when 0
        instance_exec(&self.class.__flexr_generated_actions.fetch(rule.index))
      else
        instance_exec(&rule.action)
      end
    end
__flexr_bind_generated_action(0, proc{ emit :INT, text.to_i })
  end
end
