# frozen_string_literal: true
# Generated by flexr. DO NOT EDIT.
# source: spec/fixtures/generated.flexr.rb
# spec-digest: sha256:630e6ec3baf5ded8290c405628b321aef2a8832f5a7d59f39dbec08cb8e5e3a0
# artifact-schema: 1
# runtime-abi: 1
# unicode: 15.1.0
# backend: table
# compiled: true
# eval: false
# standalone: false

require "flexr"

module GeneratedFixture
  class Lexer < Flexr::Lexer
    DIGIT = /[0-9]/
    Flexr::Generated.install_compiled!(self, { artifact: {schema_version: 1, compiler_version: "1.0.0", runtime_abi_version: 1, unicode_version: "15.1.0"}, rules: [{ index: 0, patterns: [/(?-imx:[0-9])+/], pattern_conditions: [[0, 0, false, false]], trailing: nil, action: proc{ emit :INT, text.to_i }, states: [:initial], bol_only: false, end_anchor: nil }], backend: :table, token_kind: :array, encoding: Encoding::UTF_8, declared_tokens: [], options: {}, eof_rules: {  }, states: [], inclusive_states: {initial: true}, compiled: { machines: { :initial => { state_name: :initial, dfa: {accepts: [[], [[0, 0, false, false]]], ec: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], class_count: 3, state_count: 2, start: 0, rule_ids: [0], packed: {base: [0, 1], default: [nil, nil], next: [nil, 1, 1], check: [nil, 0, 1]}} } }, states: [:initial], stats: {initial: {states: 2, classes: 3, accepting_states: 1}}, diagnostics: [] } })
    def scan_one
      return Flexr::Runtime::Interpreter.new(self).scan unless __flexr_generated_fast_path?
      machine = self.class.__flexr_compiled.machines.fetch(state)
      dfa = machine.dfa
      position = byte_pos
      return nil unless valid_utf8_at?(position)
      cursor = position
      current = dfa.start
      direct = dfa.direct
      best = nil
      accelerate = self.class.__flexr_config.options.fetch(:accel, :auto) != :none
      while cursor < buffer.bytesize || buffer.ensure_available?(cursor + 1)
        if accelerate
          region = __flexr_generated_acceleration_region(dfa, current)
          acceptance = dfa.accepts[current].first
          token_rule = acceptance && self.class.__flexr_rules.fetch(acceptance.rule_index)
          accelerated_end = __flexr_generated_accelerate(region, cursor, token_rule, position) if region
          if accelerated_end && accelerated_end > cursor
            cursor = accelerated_end
            best = __flexr_generated_acceptance(dfa, current, position, cursor, best)
            next
          end
        end
        byte = buffer.getbyte(cursor)
        consume_step!
        current = if direct
          class_id = dfa.ec[byte]
          value = direct[:nxt][(current * direct[:classes]) + class_id]
          value >= 0 ? value : nil
        else
          dfa.transition(current, byte)
        end
        break unless current
        cursor += 1
        resource_acceptance = dfa.accepts[current].first
        resource_rule = resource_acceptance && self.class.__flexr_rules.fetch(resource_acceptance.rule_index)
        defer_token_size_check!(cursor - (more_text_start || position), rule: resource_rule)
        acceptance = dfa.accepts[current].first
        if acceptance
          rule = self.class.__flexr_rules.fetch(acceptance.rule_index)
          defer_token_size_check!(cursor - (more_text_start || position), rule: rule)
          best ||= (@__flexr_generated_match ||= Flexr::Runtime::Match.new)
          best.rule = rule
          best.start_pos = position
          best.end_pos = cursor
          best.total_end_pos = cursor
        end
      end
      best
    end
    def __flexr_generated_acceleration_region(dfa, state)
      @__flexr_generated_accel_regions ||= {}
      regions = (@__flexr_generated_accel_regions[dfa] ||= Flexr::Automaton::Accel.extract(dfa).to_h { |region| [region.state, region] })
      region = regions[state]
      return unless region
      return if utf8_input? && region.bytes.any? { |byte| byte >= 128 }
      return if dfa.accepts[state].any? do |acceptance|
        rule = self.class.__flexr_rules.fetch(acceptance.rule_index)
        acceptance.bol_only || acceptance.end_anchor || rule.trailing
      end
      region
    end
    def __flexr_generated_accelerate(region, position, token_rule, token_start)
      mode = self.class.__flexr_config.options.fetch(:accel, :auto)
      cursor = position
      matched = false
      loop do
        if cursor >= buffer.bytesize
          return matched ? cursor : nil if buffer.eof_loaded?
          return matched ? cursor : nil unless buffer.ensure_available?(cursor + 1)
        end
        segment = buffer.byteslice(cursor...buffer.bytesize).to_s
        binary = segment.encoding == ::Encoding::BINARY ? segment : segment.b
        length = begin
          if %i[strscan auto].include?(mode) && defined?(::StringScanner)
            @__flexr_generated_accel_scanner ||= ::StringScanner.new("".b)
            @__flexr_generated_accel_scanner.string = binary
            @__flexr_generated_accel_scanner.pos = 0
            @__flexr_generated_accel_scanner.skip(region.regexp)
          else
            match = region.regexp.match(binary, 0)
            match && match.begin(0).zero? ? match.end(0) : nil
          end
        rescue ArgumentError
          nil
        end
        return matched ? cursor : nil unless length&.positive?
        matched = true
        cursor += length
        consume_step!(length)
        defer_token_size_check!(cursor - (more_text_start || token_start), rule: token_rule)
        return cursor if cursor < buffer.bytesize || buffer.eof_loaded?
      end
    end
    def __flexr_generated_fast_path?
      return @__flexr_generated_fast_path if defined?(@__flexr_generated_fast_path)
      @__flexr_generated_fast_path = if self.class.__flexr_config.backend == :firstmatch ||
                                      self.class.__flexr_config.options[:allow_empty_match] == true
        false
      else
        self.class.__flexr_rules.none? do |rule|
          !rule.trailing.nil?
        end
      end
    end
    def __flexr_generated_acceptance(dfa, state, start_position, cursor, best)
      dfa.accepts[state].each do |acceptance|
        next if acceptance.bol_only && !beginning_of_line?
        next if acceptance.end_anchor && !(buffer.eof?(cursor) || buffer.getbyte(cursor) == 0x0a)
        rule = self.class.__flexr_rules.fetch(acceptance.rule_index)
        defer_token_size_check!(cursor - (more_text_start || start_position), rule: rule)
        next if best && cursor < best.total_end_pos
        next if best && cursor == best.total_end_pos &&
          rule.index > best.rule.index
        best ||= (@__flexr_generated_match ||= Flexr::Runtime::Match.new)
        best.rule = rule
        best.start_pos = start_position
        best.end_pos = cursor
        best.total_end_pos = cursor
      end
      best
    end
    def __flexr_generated_execute(rule)
      case rule.index
      when 0
        instance_exec(&self.class.__flexr_generated_actions.fetch(rule.index))
      else
        instance_exec(&rule.action)
      end
    end
__flexr_bind_generated_action(0, proc{ emit :INT, text.to_i })
  end
end
