# frozen_string_literal: true
# Generated by flexr. DO NOT EDIT.
# source: spec/fixtures/generated.flexr.rb
# spec-digest: sha256:47effa790178d19a006260cf2fb4bc6b3ffbaa1ce2722068d52d37396408d2ac
# artifact-schema: 1
# runtime-abi: 1
# unicode: 15.1.0
# backend: table
# compiled: true
# eval: false
# standalone: false

require "flexr"

module GeneratedFixture
  class Lexer < Flexr::Lexer
    DIGIT = /[0-9]/
    Flexr::Generated.install_compiled!(self, { artifact: {schema_version: 1, compiler_version: "1.0.0", runtime_abi_version: 1, unicode_version: "15.1.0"}, rules: [{ index: 0, patterns: [/(?:[0-9])+/], pattern_conditions: [[0, 0, false, false]], trailing: nil, action: proc{ emit :INT, text.to_i }, states: [:initial], bol_only: false, end_anchor: nil }], backend: :table, token_kind: :array, encoding: Encoding::UTF_8, declared_tokens: [], options: {}, eof_rules: {  }, states: [], inclusive_states: {initial: true}, compiled: { machines: { :initial => { state_name: :initial, dfa: {accepts: [[], [[0, 0, false, false]]], ec: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], class_count: 3, state_count: 2, start: 0, rule_ids: [0], packed: {base: [0, 1], default: [nil, nil], next: [nil, 1, 1], check: [nil, 0, 1]}} } }, states: [:initial], stats: {initial: {states: 2, classes: 3, accepting_states: 1}}, diagnostics: [] } })
    def scan_one
      return Flexr::Runtime::Interpreter.new(self).scan unless __flexr_generated_fast_path?
      machine = self.class.__flexr_compiled.machines.fetch(state)
      dfa = machine.dfa
      position = byte_pos
      return nil unless valid_utf8_at?(position)
      cursor = position
      current = dfa.start
      direct = dfa.direct
      source = buffer.source
      best = nil
      accelerate = self.class.__flexr_config.options.fetch(:accel, :auto) != :none && !utf8_input?
      while cursor < source.bytesize || buffer.ensure_available?(cursor + 1)
        if accelerate
          region = __flexr_generated_acceleration_region(dfa, current)
          accelerated_end = __flexr_generated_accelerate(region, cursor) if region
          if accelerated_end && accelerated_end > cursor
            cursor = accelerated_end
            best = __flexr_generated_acceptance(dfa, current, position, cursor, best)
            next
          end
        end
        byte = source.getbyte(cursor)
        current = if direct
          class_id = dfa.ec[byte]
          value = direct[:nxt][(current * direct[:classes]) + class_id]
          value >= 0 ? value : nil
        else
          dfa.transition(current, byte)
        end
        break unless current
        cursor += 1
        acceptance = dfa.accepts[current].first
        if acceptance
          rule = self.class.__flexr_rules.fetch(acceptance.rule_index)
          best ||= (@__flexr_generated_match ||= Flexr::Runtime::Match.new)
          best.rule = rule
          best.start_pos = position
          best.end_pos = cursor
          best.total_end_pos = cursor
        end
      end
      best
    end
    def __flexr_generated_acceleration_region(dfa, state)
      @__flexr_generated_accel_regions ||= {}
      regions = (@__flexr_generated_accel_regions[dfa] ||= Flexr::Automaton::Accel.extract(dfa).to_h { |region| [region.state, region] })
      region = regions[state]
      return unless region
      return if dfa.accepts[state].any? do |acceptance|
        rule = self.class.__flexr_rules.fetch(acceptance.rule_index)
        acceptance.bol_only || acceptance.end_anchor || rule.trailing
      end
      region
    end
    def __flexr_generated_accelerate(region, position)
      binary = buffer.source.b
      mode = self.class.__flexr_config.options.fetch(:accel, :auto)
      match_end = if %i[strscan auto].include?(mode) && defined?(StringScanner)
        scanner = StringScanner.new(binary)
        scanner.pos = position
        length = scanner.skip(region.regexp)
        length && scanner.pos
      else
        match = region.regexp.match(binary, position)
        match && match.begin(0) == position ? match.end(0) : nil
      end
      return match_end if match_end && match_end < buffer.bytesize
      return match_end if match_end && buffer.eof_loaded?
      return unless buffer.ensure_available?(buffer.bytesize + 1)
      __flexr_generated_accelerate(region, position)
    rescue ArgumentError
      nil
    end
    def __flexr_generated_fast_path?
      return @__flexr_generated_fast_path if defined?(@__flexr_generated_fast_path)
      @__flexr_generated_fast_path = if self.class.__flexr_config.backend == :firstmatch ||
                                      self.class.__flexr_config.options[:allow_empty_match] == true
        false
      else
        self.class.__flexr_rules.none? do |rule|
          !rule.trailing.nil? || rule.patterns.any? do |pattern|
            next false unless pattern.is_a?(Regexp)
          next true if pattern.source.match?(/\\[pP]\\{/) || pattern.source.match?(/\[:(?:\^)?[a-z]+:\]/)
            self.class.__flexr_config.options[:unicode] == true && utf8_input? && pattern.source.match?(/\\[dDwWsS]/)
          end
        end
      end
    end
    def __flexr_generated_acceptance(dfa, state, start_position, cursor, best)
      dfa.accepts[state].each do |acceptance|
        next if acceptance.bol_only && !beginning_of_line?
        next if acceptance.end_anchor && !(buffer.eof?(cursor) || buffer.getbyte(cursor) == 0x0a)
        rule = self.class.__flexr_rules.fetch(acceptance.rule_index)
        defer_token_size_check!(cursor - start_position)
        next if best && cursor < best.total_end_pos
        next if best && cursor == best.total_end_pos &&
          rule.index > best.rule.index
        best ||= (@__flexr_generated_match ||= Flexr::Runtime::Match.new)
        best.rule = rule
        best.start_pos = start_position
        best.end_pos = cursor
        best.total_end_pos = cursor
      end
      best
    end
    def __flexr_generated_execute(rule)
      case rule.index
      when 0
        emit :INT, text.to_i
      else
        instance_exec(&rule.action)
      end
    end

  end
end
