# frozen_string_literal: true

require "open3"
require "rbconfig"
require "stringio"

RSpec.describe "generated artifact safety" do
  def lexer_source(preamble = "", suffix: "")
    <<~RUBY.sub("PREAMBLE", preamble).concat(suffix)
      PREAMBLErequire "flexr"
      class GeneratorSafetyLexer < Flexr::Lexer
        rule(/a/) { emit :A }
      end
    RUBY
  end

  it "inserts normal and standalone headers after supported Ruby preambles" do
    preambles = [
      "",
      "#!/usr/bin/env ruby\n",
      "# encoding: UTF-8\n",
      "# frozen_string_literal: true\n",
      "#!/usr/bin/env ruby\n# encoding: UTF-8\n# frozen_string_literal: true\n",
      "\n"
    ]

    Dir.mktmpdir("flexr-preamble-") do |directory|
      preambles.each_with_index do |preamble, index|
        path = File.join(directory, "lexer-#{index}.flexr.rb")
        File.binwrite(path, lexer_source(preamble).gsub("\n", "\r\n"))

        [false, true].each do |standalone|
          generated = Flexr::Generator.new(path, options: { standalone: standalone }).generate
          expect(generated).to include("# Generated by flexr.", "Flexr::Generated.install_compiled!")
          expect(generated).to include("module Flexr") if standalone
          expect(generated).not_to include(%(require "flexr")) if standalone
          expect(generated).to start_with("#!/usr/bin/env ruby\n") if preamble.start_with?("#!")

          header_offset = generated.index("# Generated by flexr.")
          %w[encoding frozen_string_literal].each do |marker|
            marker_offset = generated.index(marker)
            expect(header_offset).to be > marker_offset if marker_offset && marker_offset < 200
          end

          Tempfile.create(["flexr-preamble-", ".rb"]) do |file|
            file.binmode
            file.write(generated)
            file.flush
            _stdout, stderr, status = Open3.capture3(RbConfig.ruby, "-c", file.path)
            expect(status).to be_success, stderr
          end
        end
      end
    end
  end

  it "loads a standalone lexer generated without a magic comment" do
    Dir.mktmpdir("flexr-standalone-") do |directory|
      path = File.join(directory, "lexer.flexr.rb")
      output = File.join(directory, "lexer.rb")
      File.binwrite(path, lexer_source)
      Flexr::Generator.new(path, output: output, options: { standalone: true }).generate

      script = <<~RUBY
        load ARGV.fetch(0)
        abort "wrong tokens" unless GeneratorSafetyLexer.new("a").tokens == [[:A, "a"]]
      RUBY
      _stdout, stderr, status = Open3.capture3(RbConfig.ruby, "-e", script, output)
      expect(status).to be_success, stderr
    end
  end

  it "embeds only the runtime core for a compiled standalone lexer" do
    Dir.mktmpdir("flexr-standalone-core-") do |directory|
      path = File.join(directory, "lexer.flexr.rb")
      generated = Flexr::Generator.new(path, options: { standalone: true }).tap do
        File.binwrite(path, lexer_source)
      end.generate

      expect(generated.bytesize).to be < 100_000
      expect(generated).not_to include(
        "class Compiler", "class NFABuilder", "class Parser", "module Data", "class BackendCostModel"
      )
    end
  end

  it "adds the reference matcher only when a standalone lexer needs it" do
    source = <<~RUBY
      require "flexr"
      class GeneratorSafetyFirstmatchLexer < Flexr::Lexer
        backend :firstmatch
        option :experimental
        rule(/\\p{L}+/) { emit :WORD }
      end
    RUBY

    Dir.mktmpdir("flexr-standalone-matcher-") do |directory|
      path = File.join(directory, "lexer.flexr.rb")
      output = File.join(directory, "lexer.rb")
      File.binwrite(path, source)
      generated = Flexr::Generator.new(path, output: output, options: { standalone: true }).generate

      expect(generated).to include("class Parser", "module Data")
      expect(generated).not_to include("class Compiler", "class NFABuilder", "class BackendCostModel")
      script = <<~RUBY
        load ARGV.fetch(0)
        abort "wrong tokens" unless
          GeneratorSafetyFirstmatchLexer.new("日本語").tokens == [[:WORD, "日本語"]]
      RUBY
      _stdout, stderr, status = Open3.capture3(RbConfig.ruby, "-e", script, output)
      expect(status).to be_success, stderr
    end
  end

  it "preserves heredoc and DATA contents during standalone transformation" do
    source = <<~RUBY
      PAYLOAD = <<'TEXT'
      	 
      require "flexr"
      TEXT
      require "flexr"
      class GeneratorSafetyLexer < Flexr::Lexer
        rule(/a/, skip: true)
      end
      __END__
      	 
      require "flexr"
    RUBY

    Dir.mktmpdir("flexr-passthrough-") do |directory|
      path = File.join(directory, "lexer.flexr.rb")
      File.binwrite(path, source)
      generated = Flexr::Generator.new(path, options: { standalone: true }).generate

      expect(generated).to include("PAYLOAD = <<'TEXT'\n\t \nrequire \"flexr\"\nTEXT")
      expect(generated).to end_with("__END__\n\t \nrequire \"flexr\"\n")
    end
  end

  it "rejects direct, symlink, and hard-link input collisions without changing the source" do
    Dir.mktmpdir("flexr-collision-") do |directory|
      path = File.join(directory, "lexer.rb")
      source = lexer_source
      File.binwrite(path, source)
      aliases = [path, File.join(directory, "lexer-link.rb"), File.join(directory, "lexer-hard.rb")]
      File.symlink(path, aliases[1])
      File.link(path, aliases[2])

      aliases.each do |output|
        expect { Flexr::Generator.new(path, output: output).generate }
          .to raise_error(ArgumentError, /refusing to overwrite input file/)
        expect(File.binread(path)).to eq(source)
      end
    end
  end

  it "uses a non-colliding default for ordinary Ruby filenames" do
    expect(Flexr::ArtifactWriter.default_generated_path("lexer.rb")).to eq("lexer.generated.rb")
    expect(Flexr::ArtifactWriter.default_generated_path("lexer.flexr.rb")).to eq("lexer.rb")
  end

  it "keeps an ordinary Ruby input intact when the CLI chooses its default output" do
    Dir.mktmpdir("flexr-cli-output-") do |directory|
      path = File.join(directory, "lexer.rb")
      output = File.join(directory, "lexer.generated.rb")
      source = lexer_source
      File.binwrite(path, source)

      status = Flexr::CLI.run([path], out: StringIO.new, err: StringIO.new)

      expect(status).to eq(Flexr::CLI::EXIT_OK)
      expect(File.binread(path)).to eq(source)
      expect(File).to exist(output)
    end
  end

  it "refuses to import onto the input file" do
    source = <<~LEX
      %token WORD
      %%
      [a-z]+    { return WORD; }
    LEX
    Dir.mktmpdir("flexr-import-collision-") do |directory|
      path = File.join(directory, "lexer.l")
      File.binwrite(path, source)
      errors = StringIO.new

      status = Flexr::CLI.run(["import", path, "-o", path], out: StringIO.new, err: errors)

      expect(status).to eq(Flexr::CLI::EXIT_USAGE)
      expect(errors.string).to include("refusing to overwrite input file")
      expect(File.binread(path)).to eq(source)
    end
  end

  it "does not change the timestamp when generated contents are unchanged" do
    Dir.mktmpdir("flexr-noop-") do |directory|
      path = File.join(directory, "lexer.flexr.rb")
      output = File.join(directory, "lexer.rb")
      File.binwrite(path, lexer_source)
      generator = Flexr::Generator.new(path, output: output)
      generator.generate
      unchanged_time = Time.at(1_700_000_000)
      File.utime(unchanged_time, unchanged_time, output)

      expect(generator.generate).to eq(File.binread(output))
      expect(File.mtime(output)).to eq(unchanged_time)
    end
  end

  it "keeps the previous artifact intact when an atomic rename fails" do
    Dir.mktmpdir("flexr-atomic-failure-") do |directory|
      output = File.join(directory, "lexer.rb")
      File.binwrite(output, "previous")
      allow(File).to receive(:rename).and_raise(Errno::EIO, "simulated rename failure")

      expect { Flexr::ArtifactWriter.write!(output, "replacement") }.to raise_error(Errno::EIO)
      expect(File.binread(output)).to eq("previous")
      expect(Dir.children(directory)).to eq(["lexer.rb"])
    end
  end

  it "rejects generated payloads with missing or incompatible metadata" do
    payload = {
      rules: [], backend: :table, token_kind: :array, encoding: Encoding::UTF_8,
      declared_tokens: [], options: {}, states: [], inclusive_states: {}, eof_rules: {},
      compiled: { machines: {}, states: [], stats: {}, diagnostics: [] }
    }

    expect { Flexr::Generated.install_compiled!(Class.new(Flexr::Lexer), payload) }
      .to raise_error(Flexr::CompileError) { |error| expect(error.diagnostic.code).to eq("FLEXR-E020") }
    incompatible = payload.merge(
      artifact: Flexr::Generated.artifact_metadata.merge(runtime_abi_version: -1)
    )
    expect { Flexr::Generated.install_compiled!(Class.new(Flexr::Lexer), incompatible) }
      .to raise_error(Flexr::CompileError) { |error| expect(error.diagnostic.note).to include("runtime_abi_version") }
  end
end
