# frozen_string_literal: true

module Flexr
  class Generator
    RUNTIME_SOURCES = %w[
      version.rb errors.rb diagnostics.rb ir.rb
      regexp/ast.rb regexp/parser.rb regexp/normalizer.rb regexp/unsupported.rb regexp/char_class.rb
      unicode/utf8_splitter.rb unicode/data/properties.rb unicode/property.rb unicode/reference_regexp.rb unicode/case_fold.rb
      automaton/byte_class_set.rb automaton/nfa.rb automaton/dfa.rb automaton/compiler.rb
      automaton/analysis.rb automaton/minimizer.rb automaton/accel.rb
      runtime/location.rb runtime/token.rb runtime/buffer.rb runtime/errors.rb
      runtime/interpreter.rb runtime/core.rb dsl.rb lexer.rb generated.rb
    ].freeze

    def initialize(path, output: nil, eval_mode: false, options: {})
      @path = path
      @output = output
      @eval_mode = eval_mode
      @options = options
    end

    def generate
      source = File.binread(@path).force_encoding(Encoding::UTF_8)
      result = if @eval_mode
        generate_from_runtime(source)
      else
        parsed = Source::PrismReader.new(source, path: @path).read
        generate_static(parsed)
      end
      File.binwrite(@output, result) if @output
      result
    end

    private

    def generate_static(parsed)
      compiled = compile_parsed(parsed)
      payload = generated_payload(parsed, compiled)
      indent = Source::Passthrough.indentation(parsed.source, parsed.first_dsl_offset)
      install = "Flexr::Generated.install_compiled!(self, #{payload})\n#{indent}"
      result = Source::Passthrough.remove_spans(parsed.source, parsed.dsl_spans, insertion: parsed.first_dsl_offset, payload: install)
      result = result.gsub(/^\s*require [\"']flexr[\"']\s*\n/, "") if standalone?(parsed)
      digest = Digest::SHA256.hexdigest(payload)
      header = [
        "# Generated by flexr. DO NOT EDIT.",
        "# source: #{parsed.path}",
        "# spec-digest: sha256:#{digest}",
        "# backend: #{@options.fetch(:backend, parsed.config[:backend])}",
        "# compiled: true",
        "# standalone: #{standalone?(parsed)}"
      ].join("\n")
      prefix = standalone?(parsed) ? "require \"json\"\n#{embedded_runtime}\n" : ""
      result.sub(/\A(# frozen_string_literal: true\n)/) { "#{$1}#{header}\n#{prefix}" }
    end

    def generated_payload(parsed, compiled)
      definitions = parsed.rules.map do |rule|
        "{ index: #{rule.index}, patterns: #{rule.patterns.inspect}, trailing: #{rule.trailing.inspect}, " \
          "action: #{action_expression(rule.action)}, states: #{rule.states.inspect}, " \
          "bol_only: #{rule.bol_only.inspect}, end_anchor: #{rule.end_anchor.inspect} }"
      end
      "{ rules: [#{definitions.join(", ")}], " \
        "backend: #{@options.fetch(:backend, parsed.config[:backend]).inspect}, " \
        "token_kind: #{@options.fetch(:token_kind, parsed.config[:token_kind]).inspect}, " \
        "encoding: #{encoding_expression(parsed.config[:encoding])}, " \
        "declared_tokens: #{parsed.config[:declared_tokens].inspect}, " \
        "options: #{(parsed.config[:options] || {}).inspect}, " \
        "eof_rules: #{eof_rules_expression(parsed.config[:eof_rules] || {})}, " \
        "states: #{parsed.states.keys.reject { |name| name == :initial }.inspect}, " \
        "inclusive_states: #{parsed.states.transform_values { |value| value[:inclusive] }.inspect}, " \
        "compiled: #{compiled_expression(compiled)} }"
    end

    def compile_parsed(parsed)
      states = parsed.states.each_with_index.to_h do |(name, value), index|
        [name.to_sym, IR::State.new(name: name.to_sym, inclusive: value[:inclusive], id: index)]
      end
      rules = parsed.rules.map do |rule|
        IR::Rule.new(index: rule.index, patterns: rule.patterns, trailing: rule.trailing,
                     action: rule.action, states: rule.states, bol_only: rule.bol_only,
                     end_anchor: rule.end_anchor)
      end
      spec = IR::Spec.new(
        class_name: parsed.class_name, superclass: "Flexr::Lexer",
        backend: @options.fetch(:backend, parsed.config[:backend]),
        token_kind: @options.fetch(:token_kind, parsed.config[:token_kind]),
        encoding: parsed.config[:encoding], options: parsed.config[:options] || {},
        declared_tokens: parsed.config[:declared_tokens], states: states, rules: rules,
        eof_rules: parsed.config[:eof_rules] || {}, verbatim: parsed.source
      )
      Automaton::Compiler.new(spec).compile
    end

    def compiled_expression(compiled)
      machines = compiled.machines.map do |name, machine|
        dfa = machine.dfa
        data = {
          transitions: dfa.transitions,
          accepts: dfa.accepts,
          ec: dfa.ec,
          class_count: dfa.class_count,
          start: dfa.start,
          rule_ids: dfa.rule_ids
        }
        "#{name.inspect} => { state_name: #{machine.state_name.inspect}, dfa: #{data.inspect} }"
      end
      "{ machines: { #{machines.join(', ')} }, states: #{compiled.states.inspect}, stats: #{compiled.stats.inspect} }"
    end

    def standalone?(parsed)
      @options.fetch(:standalone, parsed.config[:options]&.key?(:standalone) || false)
    end

    def embedded_runtime
      RUNTIME_SOURCES.map do |relative|
        File.binread(File.expand_path(relative, __dir__))
      end.join("\n")
    end

    def encoding_expression(encoding)
      encoding == Encoding::BINARY ? "Encoding::BINARY" : "Encoding::UTF_8"
    end

    def eof_rules_expression(rules)
      pairs = rules.map { |state, action| "#{state.inspect} => #{action_expression(action)}" }
      "{ #{pairs.join(", ")} }"
    end

    def action_expression(action)
      return action if action.is_a?(String) && action.start_with?("proc")
      return action.inspect unless action.is_a?(Proc)

      "proc { emit(nil, text) }"
    end

    def generate_from_runtime(source)
      loader = Object.new
      loader.define_singleton_method(:load_spec) do
        eval(source, TOPLEVEL_BINDING, @path, 1)
      end
      loader.instance_variable_set(:@path, @path)
      loader.load_spec
      passthrough = Source::PrismReader.new(source, path: @path).read(allow_dynamic: true)
      classes = ObjectSpace.each_object(Class).select { |klass| klass.respond_to?(:__flexr_spec) }
      classes.select! do |klass|
        name = klass.name.to_s
        (passthrough.class_name.nil? || name == passthrough.class_name || name.end_with?("::#{passthrough.class_name}")) &&
          klass != Flexr::Lexer && klass.__flexr_rules.any?
      end
      klass = classes.last
      raise CompileError, "--eval could not find a Flexr::Lexer class" unless klass

      parsed = klass.__flexr_spec
      # --eval is intentionally explicit; the generated file still contains
      # executable action source, but its metadata is deterministic for this run.
      parsed = klass.__flexr_spec
      runtime_rules = parsed.rules.to_h { |rule| [rule.index, rule] }
      passthrough.rules.each do |rule|
        runtime_rule = runtime_rules.fetch(rule.index)
        rule.patterns = runtime_rule.patterns
        rule.trailing = runtime_rule.trailing
      end
      generate_static(passthrough)
    end
  end
end
